name: Java CI with Gradle

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1) 코드 체크아웃
    - uses: actions/checkout@v3

    # 2) JDK 17 설정 (필요에 따라 변경)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle  # Gradle 캐시 활성화

    # 3) Gradle 빌드 및 테스트 수행
    - name: Build and Test with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        arguments: clean build --parallel --daemon
